ApiMVCSeriesPeliculas/Models/ErrorViewModel.cs
namespace ApiMVCSeriesPeliculas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ApiMVCSeriesPeliculas/Controllers/HomeController.cs
using ApiMVCSeriesPeliculas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ApiMVCSeriesPeliculas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult NuevoPersonaje()
        {
            return View();
        }
        public IActionResult ModificarPersonaje()
        {
            return View();
        }
        public IActionResult Series()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApiMVCSeriesPeliculas/Controllers/ViewModelsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Threading.Tasks;
using System.Collections.Generic;
using ApiMVCSeriesPeliculas.Models;
using System.Text.Json;


namespace ApiMVCSeriesPeliculas.Controllers
{
    public class ViewModelsController : Controller
    {
        public IActionResult NuevoPersonaje()
        {
            return View();
        }
        public IActionResult ModificarPersonaje()
        {
            return View();
        }

        public IActionResult Series()
        {
            return View();
        }

    }
}

ApiMVCSeriesPeliculas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section WelcomeMessage {
    <div class="text-center" id="welcomeMessage">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>
}

ApiMVCSeriesPeliculas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApiMVCSeriesPeliculas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ApiMVCSeriesPeliculas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ApiMVCSeriesPeliculas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewModels" asp-action="NuevoPersonaje">Nuevo Personaje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewModels" asp-action="ModificarPersonaje">Modificar Personajes</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdownSeries" class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Series
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownSeries" id="selectSeries">
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Contenedor de la imagen de la serie -->
    <div class="container" id="serieImagenContainer" style="display: none;">
        <div class="card" style="height: 100%; width: 35%">
            <div>
                <img id="serieImagen" class="card-img-top" src="#" alt="Imagen de la serie" />
            </div>
            <div class="card-body">
                <h5 class="card-title" id="serieNombre"></h5>
                <p id="puntuacion"></p>
                <button id="personajesButton"type="button" class="btn btn-success" style="width: 100%">Personajes</button>
            </div>
        </div>
    </div>

    <!-- Contenedor de la lista de personajes -->
    <div class="container mt-3" id="personajesContainer" style="display: none;">
        <h3>Personajes</h3>
        <ul id="listaPersonajes">
        </ul>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ApiMVCSeriesPeliculas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @RenderSection("WelcomeMessage", required: false)
    <script>
        $(document).ready(function () {
            function cargarSeries() {
                var urlSeries = 'https://apiseriespersonajes.azurewebsites.net/api/Series';

                $.ajax({
                    url: urlSeries,
                    type: 'GET',
                    dataType: 'json',
                    success: function (series) {
                        var select = $('#selectSeries');

                        $.each(series, function (index, serie) {


                            select.append('<a class="dropdown-item" href="#" data-imagen="' + serie.imagen + '" data-nombre="' + serie.nombre + '" data-id="' + serie.idSerie + '" data-puntuacion="' + serie.puntuacion + '/">' + serie.nombre + '</a>');
                        });
                        $('.dropdown-item').click(function () {
                            var container = document.getElementById("serieImagenContainer");
                            container.style.display = "flex";
                            container.style.justifyContent = "center";
                            var imagen = $(this).data('imagen');
                            var nombre = $(this).data('nombre');
                            var idSerie = $(this).data('id');
                            var puntuacion = $(this).data('puntuacion');
                            $('#serieImagen').attr('src', imagen);
                            $('#serieNombre').text(nombre);
                            $('#puntuacion').text('Puntuacion: '+puntuacion);
                            $('#serieImagenContainer').show();
                            $('#personajesContainer').hide();
                            $('#welcomeMessage').hide();

                            $('#personajesButton').off('click').click(function () {
                                cargarPersonajes(idSerie);
                            });
                        });
                    },
                    error: function (xhr, status, error) {
                        console.error('Error al cargar las series:', error);
                    }
                });
            }

            function cargarPersonajes(idSerie) {
                var urlPersonajes = 'https://apiseriespersonajes.azurewebsites.net/api/Series/PersonajesSerie/' + idSerie;

                $.ajax({
                    url: urlPersonajes,
                    type: 'GET',
                    dataType: 'json',
                    success: function (personajes) {
                        var tableHTML = '<div class="mb-3"><button id="volverButton" type="button" class="btn btn-danger">Volver</button></div>';
                        tableHTML += '<table class="table" style=\"background-color: #1f2121; color: white; \"><thead><tr><th>Personajes</th><th>Imagen</th></tr></thead><tbody>';
                        $.each(personajes, function (index, personaje) {
                            tableHTML += '<tr>';
                            tableHTML += '<td>' + personaje.nombre + '</td>';
                            tableHTML += '<td><img src="' + personaje.imagen + '" alt="' + personaje.nombre + '" style="max-width: 200px; max-height: 200px;"></td>';
                            tableHTML += '</tr>';
                        });
                        tableHTML += '</tbody></table>';
                        $('#personajesContainer').html(tableHTML).show();
                        $('#serieImagenContainer').hide();

                        $('#volverButton').click(function () {
                            $('#personajesContainer').hide();
                            $('#serieImagenContainer').show();
                        });

                        var td = document.getElementsByTagName("td");
                        for (var i = 0; i < td.length; i++) {
                            td[i].style.border = "1px solid gray";
                        }
                        
                    },
                    error: function (xhr, status, error) {
                        console.error('Error al cargar los personajes:', error);
                    }
                });
            }

            cargarSeries();

        });
    </script>
</body>
</html>

ApiMVCSeriesPeliculas/Views/ViewModels/ModificarPersonaje.cshtml
@section scripts {
    <script>
        $(document).ready(function () {
            recuperarSeries();
            recuperarPersonajes();
        });
        // FUNCIONES SERIES
        // recuperarSeries() | Funcion que permite recoger las series almacenadas dentro de la webApi
        function recuperarSeries() {
            // Reset del select
            var select = $('#selectSerie');
            select.empty();
            select.append('<option selected disabled>Opcion...</option>');
            // Funcion para recoger el JSON
            $.getJSON('https://apiseriespersonajes.azurewebsites.net/api/Series', function (data) {
                $.each(data, function (key, value) {
                    select.append('<option value="' + value.idSerie + '">' + value.nombre + '</option>');
                });
            });
        };

        // Action event select Series
        $('#selectSerie').on('change', function () {
            cambiarInfoSerie($('#selectSerie option:selected').val())
        });

        // cambiarInfoSerie(int idSerie) | Funcion que cambiar la informacion mostrada en el div info-serie
        function cambiarInfoSerie(idSerie) {
            //Reset del div
            var divinfo = $('#info-serie')
            divinfo.empty()
            // Funcion para recoger el JSON
            $.getJSON('https://apiseriespersonajes.azurewebsites.net/api/Series/' + idSerie, function (data) {
                divinfo.append('<h2 class=\"text-danger\">' + data.nombre + '</h2>');
                divinfo.append('<img src=\"' + data.imagen + '\" style = \"width: 35%;\"/>');
            })
        }

        // FUNCIONES PERSONAJES
        // recuperarPersonajes() | Funcion que permite recoger los personajes almacenadas dentro de la webApi
        function recuperarPersonajes() {
            // Reset del select
            var select = $('#selectPersonaje');
            select.empty();
            select.append('<option selected disabled>Opcion...</option>');
            // Funcion para recoger el JSON
            $.getJSON('https://apiseriespersonajes.azurewebsites.net/api/Personajes', function (data) {
                $.each(data, function (key, value) {
                    select.append('<option value="' + value.idPersonaje + '">' + value.nombre + '</option>');
                });
            });
        };

        // Action event select Personajes
        $('#selectPersonaje').on('change', function () {
            cambiarInfoPersonaje($('#selectPersonaje option:selected').val())
        });

        // cambiarInfoPersonaje(int idSerie) | Funcion que cambiar la informacion mostrada en el div info-personaje
        function cambiarInfoPersonaje(idPersonaje) {
            //Reset del div
            var divinfo = $('#info-personaje')
            divinfo.empty()
            // Funcion para recoger el JSON
            $.getJSON('https://apiseriespersonajes.azurewebsites.net/api/Personajes/' + idPersonaje, function (data) {
                divinfo.append('<h2 class=\"text-primary\">' + data.nombre + '</h2>');
                divinfo.append('<img src=\"' + data.imagen + '\" style = \"width: 35%;\"/>');
            })
        }

        // FUNCIONES BUTTON
        // Action event select Personajes
        $('#btn-guardar').on('click', function () {
            guardarCambios($('#selectPersonaje option:selected').val(), $('#selectSerie option:selected').val())
            $('#selectSerie').empty()
            recuperarSeries()
            $('#selectPersonaje').empty()
            recuperarPersonajes()
            $('#info-serie').empty()
            $('#info-personaje').empty()
        });

        // guardarCambios(idPersonaje,idSerie)
        function guardarCambios(idPersonaje, idSerie) {
            var urlSave = 'https://apiseriespersonajes.azurewebsites.net/api/Personajes/' + idPersonaje + '/' + idSerie;
            $.ajax({
                url: urlSave,
                type: 'PUT',
                success: function (data) {
                    Swal.fire({
                        icon: 'success',
                        title: '¡Personaje modificado exitosamente!',
                        showConfirmButton: false,
                        timer: 1500
                    });
                },
                error: function (msg) {
                    Swal.fire({
                        icon: 'error',
                        title: '¡Error al modificar',
                        showConfirmButton: false,
                        timer: 1500
                    });
                }
            })
        }

    </script>
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApiMVCSeriesPeliculas</title>
</head>
<body>
    <div class="row mb-3">
        <div class="col-6 d-flex justify-content-start">
            <h1 class="text-primary">Personajes y Series</h1>
        </div>
        <div class="col-6 d-flex justify-content-end">
            <button type="button" class="btn btn-success px-3">
                <a asp-controller="Home" asp-action="Index" style="color: white; margin: 1rem 0 0 0; text-decoration:none;">
                    Volver a Inicio
                </a>
            </button>
        </div>
    </div>
    <div class="card p-3 bg-light">

        <label for="serie">Seleccione una serie:</label>
        <select class="form-select mb-3" id="selectSerie">
        </select>

        <label for="personaje">Seleccione un personaje:</label>
        <select class="form-select mb-3" id="selectPersonaje">
        </select>

        <div class="row">
            <div class="col d-flex justify-content-center">
                <button type="button" id="btn-guardar" class="btn btn-primary" style="color: white; margin: 1rem 0 0 0;">
                    Guardar Cambios
                </button>
            </div>
        </div>

    </div>

    <div id="info-serie" class="text-center">
    </div>

    <div id="info-personaje" class="text-center">
    </div>

</body>
</html>

ApiMVCSeriesPeliculas/Views/ViewModels/NuevoPersonaje.cshtml
@section scripts
{
    <script>
        $(document).ready(function () {
            function cargarSeries() {
                var urlSeries = 'https://apiseriespersonajes.azurewebsites.net/api/Series';

                $.ajax({
                    url: urlSeries,
                    type: 'GET',
                    dataType: 'json',
                    success: function (series) {
                        var select = $('#selectSeries');
                        select.empty();

                        select.append('<option selected disabled class="muted">Seleccione una serie...</option>');

                        $.each(series, function (index, serie) {
                            select.append('<option value="' + serie.idSerie + '">' + serie.nombre + '</option>');
                        });
                    },
                    error: function (error) {
                        console.error('Error al cargar las series:', error);
                    }
                });
            }

            cargarSeries();


        });
        function nuevoPersonaje(personaje) {
            var url = 'https://apiseriespersonajes.azurewebsites.net/api/Personajes';
            $.ajax({
                url: url,
                type: 'POST',
                data: personaje,
                contentType: "application/json;charset=utf-8",
                success: function (data) {
                    $('#form')[0].reset();
                    Swal.fire({
                        icon: 'success',
                        title: '¡Personaje añadido exitosamente!',
                        showConfirmButton: false,
                        timer: 1500
                    });

                },
                error: function (error) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error al añadir personaje!',
                        showConfirmButton: false,
                        timer: 1500
                    });
                    console.error('Error al añadir el personaje:', error);
                }
            });
        }

        $('#btnNuevoPersonaje').on('click', function (event) {
            event.preventDefault();
            var personaje = {
                nombre: $('#txtnombre').val(),
                imagen: $('#txtimagen').val(),
                idSerie: parseInt($('#selectSeries option:selected').val()) // Obtener idSerie en lugar del nombre de la serie y parsear a int
            };
            nuevoPersonaje(JSON.stringify(personaje));
        });

    </script>
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ApiMVCSeriesPeliculas</title>
</head>
<body>
    <div class="row mb-3">
        <div class="col-6 d-flex justify-content-start">
            <h1 class="text-primary">Nuevo Personaje</h1>
        </div>
        <div class="col-6 d-flex justify-content-end">
            <button type="button" class="btn btn-success px-3">
                <a asp-controller="Home" asp-action="Index" style="color: white; margin: 1rem 0 0 0; text-decoration:none;">
                    Volver a Inicio
                </a>
            </button>
        </div>

    </div>

    <form method="post"  enctype="multipart/form-data" id="form" class="card p-3 bg-light">
        <label for="nombre">Introduce nombre del personaje</label>
        <input type="text" name="nombre" class="form-control mb-3" id="txtnombre" placeholder="Nombre..."/>

        <label for="imagen">Introduce url de la imagen del personaje</label>
        <input type="text" name="imagen" class="form-control mb-3" id="txtimagen" placeholder="URL..." />

        <label for="nombre">Introduce serie a la que pertenece el personaje</label>
        <select class="form-select mb-3" id="selectSeries">
        </select>

        <div class="row mt-3">
            <div class="col d-flex justify-content-center">
                <button type="button" id="btnNuevoPersonaje" class="btn btn-primary btn-lg my-3">
                    Añadir Personaje
                </button>
            </div>

        </div>

    </form>
    

</body>
</html>

ApiMVCSeriesPeliculas/Views/ViewModels/Series.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}